UNIVERSITIES = [
  "Babson College",
  "Brigham Young University",
  "Brown University",
  "Bryn Mawr",
  "California Institute of Technology",
  "Columbia University",
  "Cornell University",
  "Duke University",
  "Georgetown University",
  "Georgia Institute of Technology",
  "Harvard University",
  "Massachusetts Institute of Technology",
  "New York University",
  # "Ohio State University",
  # "Pennsylvania State University",
  # "Rhode Island School of Design",
  "Stanford University",
  "Texas A&M",
  "University of California, Berkeley",
  # "University of California, Davis",
  "University of California, Irvine",
  "University of California, San Diego",
  "University of Chicago",
  "University of Evansville",
  "University of Miami",
  "University of Michigan",
  "University of Oregon",
  "University of Pennsylvania",
  "University of Southern California",
  "University of Virginia",
  "Worcester Polytechnic Institute",
  "Yale University"
]